workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: | 
          npm install
      - name: Build Web Project
        script: | 
          npm run build
      - name: Capacitor Sync
        script: | 
          npx cap sync ios
      - name: Build iOS with Xcode
        script: | 
          # Comando para build usando Swift Package Manager (sem Pods)
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release archive -archivePath ios/App/App.xcarchive CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/App.xcarchive
      - /tmp/xcodebuild_logs/*.log